generator:
  class: sfPropelGenerator
  param:
    model_class:           GcArea
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gc_area
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        max_per_page:  10
        title:  Listado de areas
        batch_actions:  {}
        display:  [area, slug, phone]
      filter:  ~
      form:
        display: [area, phone]
      edit:
        title:  Editando el área "%%area%%"
      new:
        title:  Nueva area        
