generator:
  class: sfPropelGenerator
  param:
    model_class:           GcFiltroSender
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gc_filtro_sender
    with_propel_route:     1

    config:
      actions: ~
      fields:
        email:     { label: Correo }
        rule:      { label: Regla }
        prioridad: { label: Prioridad }
      list:
        max_per_page: 10
        title:  Filtros de salida
        display:  [email, rule, prioridad]
      filter:
        display:  [email, rule, prioridad]
      form:    ~
      edit:
        title: Editando el filtro "%%email%%"
      new:
        title: Nuevo flitro de salida
