<?php



/**
 * Skeleton subclass for performing query and update operations on the 'gc_filtro_sender' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Thu Sep 23 12:34:18 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class GcFiltroSenderQuery extends BaseGcFiltroSenderQuery {

} // GcFiltroSenderQuery
